SecRuleEngine On
SecRequestBodyAccess On
SecRequestBodyLimit 20971520
SecRequestBodyNoFilesLimit 1048576
SecRequestBodyLimitAction Reject
SecResponseBodyAccess Off
SecTmpDir /tmp
SecDataDir /tmp
SecAuditEngine RelevantOnly
SecAuditLogFormat JSON
SecAuditLogType Serial
SecAuditLog /var/log/openresty/modsecurity-audit.json
SecAuditLogRelevantStatus "^(?:5|4(?!04))"

Include /etc/openresty/modsecurity/owasp-crs/crs-setup.conf
Include /etc/openresty/modsecurity/owasp-crs/rules/*.conf
Include /etc/openresty/modsecurity/custom/*.conf
